(((lambda (f)
    ((lambda (x) (f (lambda (g xs) ((x x) g xs))))
     (lambda (x) (f (lambda (g xs) ((x x) g xs))))))
  (lambda (map)
    (lambda (f xs)
      (cond ((null xs) '())
            ('t (cons (f (car xs))
                      (map f (cdr xs))))))))
 (lambda (x) (cons 'seen (cons x '())))
 '(a b c))
